// ── src/i18n/i18n.js ─────────────────────────────────────────────────────────
// Instalar dependencias:  npm install i18next react-i18next
// Importar este archivo una sola vez en tu main.jsx / index.jsx:
//   import "./i18n/i18n";
// ─────────────────────────────────────────────────────────────────────────────
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
    // ── ESPAÑOL ───────────────────────────────────────────────────────────────
    es: {
        translation: {
            nav: {
                buscar: "Buscar", inicio: "Inicio", actividad: "Actividad",
                retirar: "Retirar Dinero", depositar: "Depositar Dinero",
                transferir: "Transferir Dinero", ayuda: "Ayuda",
            },
            cli: {
                cargando: "Cargando datos...",
                sin_sesion: "No se encontró el usuario en sesión.",
                sin_nombre: "No se encontró el nombre del usuario en sesión.",
                error_carga: "Error al cargar los datos del usuario.",
                cuenta: "Cuenta", mostrar_datos: "Mostrar datos", ocultar_datos: "Ocultar datos",
                numero: "Número", saldo: "Saldo", estado: "Estado",
                titular: "Titular", vence: "Vence", tipo: "Tipo",
                ultimas_transacciones: "Últimas transacciones",
                sin_transacciones: "No hay transacciones registradas.",
                col_fecha: "Fecha", col_tipo: "Tipo", col_metodo: "Método",
                col_monto: "Monto", col_descripcion: "Descripción",
                col_destinatario: "Destinatario", col_estado: "Estado",
            },
            act: {
                cargando: "Cargando actividad…", sin_sesion: "No hay sesión activa.",
                total_depositos: "Total Depósitos", total_retiros: "Total Retiros",
                transferencias: "Transferencias", balance_neto: "Balance neto",
                csv: "CSV", pdf: "PDF", exportando: "Exportando…",
                sin_datos_exportar: "Sin datos para exportar.", error_exportar: "Error al exportar.",
                actividad_mensual: "Actividad mensual", barras: "Barras",
                linea: "Línea", distribucion: "Distribución",
                depositos: "Depósitos", retiros: "Retiros",
                buscar_placeholder: "Buscar (Netflix, supermercado…)",
                todos_tipos: "Todos los tipos", todas_cuentas: "Todas las cuentas",
                filtrar: "Filtrar", limpiar: "Limpiar",
                filtros_activos: "Filtros activos — {{count}} resultado(s)",
                transacciones_tab: "Transacciones", cuentas_tab: "Cuentas vinculadas",
                col_id: "#", col_fecha: "Fecha", col_tipo: "Tipo", col_metodo: "Método",
                col_monto: "Monto", col_saldo_post: "Saldo Post.",
                col_descripcion: "Descripción", col_destinatario: "Destinatario", col_estado: "Estado",
                sin_transacciones: "Sin transacciones para los filtros seleccionados.",
                pg_info: "{{actual}}/{{total}} · {{count}} transacciones",
                principal: "Principal", sin_saldo: "Sin saldo registrado",
                vence: "vence", tipo_cuenta_label: "Posición",
            },
            dep: {
                cargando_sesion: "Cargando datos de sesión…",
                sin_sesion: "No se encontró sesión activa.",
                error_sesion: "Error al cargar datos de sesión.",
                paso_tipo: "Tipo", paso_monedas: "Monedas", paso_monto: "Monto",
                paso_seguridad: "Seguridad", paso_confirmar: "Confirmar",
                p0_titulo: "¿Qué tipo de depósito deseas realizar?",
                tipo_directo: "Depósito Directo",
                tipo_directo_desc: "Acredita en la misma moneda que entregas",
                tipo_conversion: "Depósito con Conversión",
                tipo_conversion_desc: "Convierte a otra moneda al acreditar",
                p1_titulo: "Moneda y monto",
                moneda_entrega: "Moneda que entregas", moneda_acreditar: "Moneda a acreditar",
                tipo_tasa: "Tipo de tasa", metodo_deposito: "Método de depósito",
                monto_label: "Monto a depositar",
                preview_recibiras: "Recibirás", preview_en_cuenta: "en tu cuenta.",
                cargando_tasas: "Cargando tasas…", equiv_bob: "Equivalente en BOB",
                recibiras_en: "Recibirás en", tasa_label: "Tasa",
                p2_titulo: "Verificación de seguridad",
                p2_sub: "Ingresa tu contraseña y PIN para confirmar",
                cuenta_label: "Cuenta", tarjeta_label: "Tarjeta",
                contrasena: "Contraseña", pin: "PIN de tarjeta",
                p3_titulo: "Resumen del depósito",
                res_tipo: "Tipo", res_entregas: "Entregas", res_acredita: "Se acredita",
                res_metodo: "Método", res_correo: "Correo",
                procesando: "Procesando…", confirmar: "✓ Confirmar depósito",
                exito_titulo: "¡Depósito exitoso!", exito_recibido: "Monto recibido",
                exito_acreditado: "Monto acreditado", exito_tasa: "Tasa aplicada",
                otro_deposito: "Hacer otro depósito",
                continuar: "Continuar →", atras: "← Atrás",
                mon_BOB: "Boliviano", mon_USD: "Dólar", mon_EUR: "Euro",
                mon_BRL: "Real brasileño", mon_ARS: "Peso argentino",
                mon_CLP: "Peso chileno", mon_PEN: "Sol peruano", mon_COP: "Peso colombiano",
            },
            ret: {
                paso_datos: "Datos", paso_moneda: "Moneda",
                paso_confirmar: "Confirmar", paso_listo: "Listo",
                f0_titulo: "¿Cuánto quieres retirar?",
                autenticacion: "Autenticación",
                num_tarjeta: "Número de tarjeta",
                pin: "PIN",
                ver_opciones: "Ver opciones →",
                f1_titulo: "¿En qué moneda retiras?",
                f1_sub_inicio: "Retiro de",
                f1_sub_fin: "elige cómo quieres recibir el efectivo",
                recibes: "Recibes",
                disponible: "Disponible",
                sin_saldo: "Sin saldo",
                saldo_insuf_title: "Saldo insuficiente en esta moneda",
                cambiar_monto: "← Cambiar monto",
                f2_titulo: "Confirmar conversión",
                f2_sub_ini: "No tienes saldo en",
                f2_sub_fin: "Se convertirá desde tu saldo en BOB.",
                conv_retiras: "Retiras",
                conv_bob: "BOB a descontar",
                conv_saldo_bob: "Saldo BOB actual",
                cambiar_moneda: "← Cambiar moneda",
                confirmar_retiro: "✓ Confirmar retiro",
                exito_titulo: "¡Retiro exitoso!",
                res_solicitado: "Solicitado",
                res_entregado: "Entregado",
                res_bob_desc: "BOB descontados",
                res_equiv_bob: "Equiv. BOB",
                res_tasa: "Tasa aplicada",
                otro_retiro: "Hacer otro retiro",
                error_retiro: "No se pudo completar el retiro.",
            },
            trf: {
                cargando_sesion: "Cargando datos de sesión…",
                sin_sesion: "No se encontró sesión activa.",
                error_sesion: "Error al cargar datos de sesión.",
                paso_tipo: "Tipo", paso_cuentas: "Cuentas", paso_monto: "Monto",
                paso_seguridad: "Seguridad", paso_confirmar: "Confirmar",
                p0_titulo: "¿Qué tipo de transferencia deseas realizar?",
                tipo_directa: "Transferencia Directa",
                tipo_directa_desc: "Transfiere en la misma moneda",
                tipo_conversion: "Transferencia con Conversión",
                tipo_conversion_desc: "Convierte la moneda al transferir",
                p1_titulo: "Cuentas de origen y destino",
                cuenta_origen: "Cuenta origen",
                cuenta_origen_hint: "Tu cuenta activa",
                cuenta_destino: "Cuenta destino",
                cuenta_destino_placeholder: "Número de cuenta destino",
                descripcion: "Descripción (opcional)",
                descripcion_placeholder: "Ej: Pago de deuda, alquiler…",
                misma_cuenta_warn: "La cuenta origen y destino no pueden ser la misma.",
                p2_titulo: "Monto y moneda",
                moneda_debitar: "Moneda a debitar",
                moneda_acreditar: "Moneda a acreditar",
                disponible: "Disponible",
                tipo_tasa: "Tipo de tasa",
                metodo: "Método",
                monto_label: "Monto a transferir",
                preview_recibira: "El destinatario recibirá",
                cargando_tasas: "Cargando tasas…",
                equiv_bob: "Equivalente en BOB",
                recibira_en: "Recibirá en",
                tasa_label: "Tasa",
                p3_titulo: "Verifica los datos",
                p3_sub: "Revisa que los datos sean correctos antes de continuar",
                p4_titulo: "Resumen de la transferencia",
                res_tipo: "Tipo",
                res_debitar: "Monto a debitar",
                res_acreditar: "Monto a acreditar",
                sin_saldo_moneda: "Sin saldo en {{moneda}}. Se usarán {{monto}} desde tu saldo en BOB.",
                bob_necesarios: "BOB necesarios",
                bob_disponibles: "BOB disponibles",
                destino_recibira: "El destino recibirá",
                procesando: "Procesando…",
                confirmar: "✓ Confirmar transferencia",
                confirmar_conversion: "✓ Confirmar con conversión BOB",
                cancelar: "Cancelar",
                exito_titulo: "¡Transferencia exitosa!",
                exito_debitado: "Monto debitado",
                exito_acreditado: "Monto acreditado",
                exito_tasa: "Tasa aplicada",
                otra_transferencia: "Hacer otra transferencia",
                continuar: "Continuar →",
                atras: "← Atrás",
                mon_BOB: "Boliviano", mon_USD: "Dólar", mon_EUR: "Euro",
                mon_BRL: "Real brasileño", mon_ARS: "Peso argentino",
                mon_CLP: "Peso chileno", mon_PEN: "Sol peruano", mon_COP: "Peso colombiano",
            },
            login: {
                titulo: "Inicio de sesión",
                correo: "Correo electrónico",
                contrasena: "Contraseña",
                verificando: "Verificando...",
                iniciar: "Iniciar",
                quiero: "Quiero",
                registrarme: "Registrarme",
                error_credenciales: "Credenciales incorrectas",
            },
            reg: {
                paso_correo: "Correo", paso_verificar: "Verificar", paso_datos: "Datos",
                paso_cuenta: "Cuenta", paso_confirmar: "Confirmar",
                p0_titulo: "Crea tu cuenta", p0_sub: "Ingresa tu correo para empezar. Te enviaremos un código de verificación.",
                correo_label: "Correo electrónico",
                enviando: "Enviando código…", enviar_codigo: "Enviar código de verificación →",
                codigo_enviado_a: "Código enviado a",
                tengo_codigo: "Tengo mi código →",
                p1_titulo: "Verifica tu correo", p1_sub: "Ingresa el código de 6 dígitos que enviamos a tu correo.",
                codigo_label: "Código de verificación",
                verificando: "Verificando…", verificar: "Verificar →",
                no_recibiste: "¿No recibiste el código?", reenviar: "Reenviar",
                p2_titulo: "Datos personales", p2_sub: "Completa tu información para crear la cuenta.",
                nombre: "Nombre", apellido: "Apellido", telefono: "Teléfono",
                edad: "Edad", direccion: "Dirección", contrasena: "Contraseña",
                contrasena_placeholder: "Mínimo 8 caracteres",
                p3_titulo: "Tipo de cuenta y tarjeta", p3_sub: "Elige las opciones que mejor se adapten a ti.",
                tipo_cuenta_label: "Tipo de cuenta", tipo_tarjeta_label: "Tipo de tarjeta",
                cuenta_ahorro: "Ahorro", cuenta_ahorro_desc: "Ideal para guardar y ahorrar",
                cuenta_corriente: "Corriente", cuenta_corriente_desc: "Para uso diario y transacciones",
                tarjeta_debito: "Débito", tarjeta_debito_desc: "Gasta solo lo que tienes",
                tarjeta_credito: "Crédito", tarjeta_credito_desc: "Compra ahora y paga después",
                p4_titulo: "Confirmar registro", p4_sub: "Revisa tus datos antes de crear la cuenta.",
                anios: "años", registrando: "Registrando…", crear_cuenta: "✓ Crear cuenta",
                exito_titulo: "¡Cuenta creada!", exito_msg: "Tu cuenta fue registrada exitosamente.",
                exito_correo_aviso: "Hemos enviado tu número de tarjeta, número de cuenta y PIN al correo:",
                exito_redireccion: "Revisa tu bandeja de entrada (y spam). Serás redirigido automáticamente en unos segundos...",
                ir_login: "Ir al Login ahora",
                error_crear: "Ocurrió un error al crear la cuenta",
                atras: "Atrás", continuar: "Continuar →",
            },
            lang: { titulo: "Idioma" },
        },
    },

    // ── ENGLISH ───────────────────────────────────────────────────────────────
    en: {
        translation: {
            nav: {
                buscar: "Search", inicio: "Home", actividad: "Activity",
                retirar: "Withdraw Money", depositar: "Deposit Money",
                transferir: "Transfer Money", ayuda: "Help",
            },
            cli: {
                cargando: "Loading data...",
                sin_sesion: "No user found in session.",
                sin_nombre: "No username found in session.",
                error_carga: "Error loading user data.",
                cuenta: "Account", mostrar_datos: "Show data", ocultar_datos: "Hide data",
                numero: "Number", saldo: "Balance", estado: "Status",
                titular: "Holder", vence: "Expires", tipo: "Type",
                ultimas_transacciones: "Latest transactions",
                sin_transacciones: "No transactions recorded.",
                col_fecha: "Date", col_tipo: "Type", col_metodo: "Method",
                col_monto: "Amount", col_descripcion: "Description",
                col_destinatario: "Recipient", col_estado: "Status",
            },
            act: {
                cargando: "Loading activity…", sin_sesion: "No active session.",
                total_depositos: "Total Deposits", total_retiros: "Total Withdrawals",
                transferencias: "Transfers", balance_neto: "Net Balance",
                csv: "CSV", pdf: "PDF", exportando: "Exporting…",
                sin_datos_exportar: "No data to export.", error_exportar: "Export error.",
                actividad_mensual: "Monthly Activity", barras: "Bars",
                linea: "Line", distribucion: "Distribution",
                depositos: "Deposits", retiros: "Withdrawals",
                buscar_placeholder: "Search (Netflix, supermarket…)",
                todos_tipos: "All types", todas_cuentas: "All accounts",
                filtrar: "Filter", limpiar: "Clear",
                filtros_activos: "Active filters — {{count}} result(s)",
                transacciones_tab: "Transactions", cuentas_tab: "Linked Accounts",
                col_id: "#", col_fecha: "Date", col_tipo: "Type", col_metodo: "Method",
                col_monto: "Amount", col_saldo_post: "Post-Balance",
                col_descripcion: "Description", col_destinatario: "Recipient", col_estado: "Status",
                sin_transacciones: "No transactions for the selected filters.",
                pg_info: "{{actual}}/{{total}} · {{count}} transactions",
                principal: "Main", sin_saldo: "No balance recorded",
                vence: "expires", tipo_cuenta_label: "Position",
            },
            dep: {
                cargando_sesion: "Loading session data…",
                sin_sesion: "No active session found.",
                error_sesion: "Error loading session data.",
                paso_tipo: "Type", paso_monedas: "Currencies", paso_monto: "Amount",
                paso_seguridad: "Security", paso_confirmar: "Confirm",
                p0_titulo: "What type of deposit would you like to make?",
                tipo_directo: "Direct Deposit",
                tipo_directo_desc: "Credits in the same currency you provide",
                tipo_conversion: "Deposit with Conversion",
                tipo_conversion_desc: "Converts to another currency when credited",
                p1_titulo: "Currency and amount",
                moneda_entrega: "Currency you provide", moneda_acreditar: "Currency to credit",
                tipo_tasa: "Rate type", metodo_deposito: "Deposit method",
                monto_label: "Amount to deposit",
                preview_recibiras: "You will receive", preview_en_cuenta: "in your account.",
                cargando_tasas: "Loading rates…", equiv_bob: "Equivalent in BOB",
                recibiras_en: "You will receive in", tasa_label: "Rate",
                p2_titulo: "Security verification",
                p2_sub: "Enter your password and PIN to confirm",
                cuenta_label: "Account", tarjeta_label: "Card",
                contrasena: "Password", pin: "Card PIN",
                p3_titulo: "Deposit summary",
                res_tipo: "Type", res_entregas: "You provide", res_acredita: "Credited as",
                res_metodo: "Method", res_correo: "Email",
                procesando: "Processing…", confirmar: "✓ Confirm deposit",
                exito_titulo: "Deposit successful!", exito_recibido: "Amount received",
                exito_acreditado: "Amount credited", exito_tasa: "Applied rate",
                otro_deposito: "Make another deposit",
                continuar: "Continue →", atras: "← Back",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Brazilian Real", mon_ARS: "Argentine Peso",
                mon_CLP: "Chilean Peso", mon_PEN: "Peruvian Sol", mon_COP: "Colombian Peso",
            },
            ret: {
                paso_datos: "Details", paso_moneda: "Currency",
                paso_confirmar: "Confirm", paso_listo: "Done",
                f0_titulo: "How much do you want to withdraw?",
                autenticacion: "Authentication",
                num_tarjeta: "Card number",
                pin: "PIN",
                ver_opciones: "See options →",
                f1_titulo: "In which currency do you withdraw?",
                f1_sub_inicio: "Withdrawal of",
                f1_sub_fin: "choose how you want to receive the cash",
                recibes: "You receive",
                disponible: "Available",
                sin_saldo: "No balance",
                saldo_insuf_title: "Insufficient balance in this currency",
                cambiar_monto: "← Change amount",
                f2_titulo: "Confirm conversion",
                f2_sub_ini: "You have no balance in",
                f2_sub_fin: "It will be converted from your BOB balance.",
                conv_retiras: "You withdraw",
                conv_bob: "BOB to deduct",
                conv_saldo_bob: "Current BOB balance",
                cambiar_moneda: "← Change currency",
                confirmar_retiro: "✓ Confirm withdrawal",
                exito_titulo: "Withdrawal successful!",
                res_solicitado: "Requested",
                res_entregado: "Delivered",
                res_bob_desc: "BOB deducted",
                res_equiv_bob: "BOB equiv.",
                res_tasa: "Applied rate",
                otro_retiro: "Make another withdrawal",
                error_retiro: "Could not complete the withdrawal.",
            },
            trf: {
                cargando_sesion: "Loading session data…",
                sin_sesion: "No active session found.",
                error_sesion: "Error loading session data.",
                paso_tipo: "Type", paso_cuentas: "Accounts", paso_monto: "Amount",
                paso_seguridad: "Security", paso_confirmar: "Confirm",
                p0_titulo: "What type of transfer would you like to make?",
                tipo_directa: "Direct Transfer",
                tipo_directa_desc: "Transfer in the same currency",
                tipo_conversion: "Transfer with Conversion",
                tipo_conversion_desc: "Convert currency when transferring",
                p1_titulo: "Source and destination accounts",
                cuenta_origen: "Source account",
                cuenta_origen_hint: "Your active account",
                cuenta_destino: "Destination account",
                cuenta_destino_placeholder: "Destination account number",
                descripcion: "Description (optional)",
                descripcion_placeholder: "E.g.: Debt payment, rent…",
                misma_cuenta_warn: "Source and destination accounts cannot be the same.",
                p2_titulo: "Amount and currency",
                moneda_debitar: "Currency to debit",
                moneda_acreditar: "Currency to credit",
                disponible: "Available",
                tipo_tasa: "Rate type",
                metodo: "Method",
                monto_label: "Amount to transfer",
                preview_recibira: "The recipient will receive",
                cargando_tasas: "Loading rates…",
                equiv_bob: "Equivalent in BOB",
                recibira_en: "Will receive in",
                tasa_label: "Rate",
                p3_titulo: "Verify details",
                p3_sub: "Check that the details are correct before continuing",
                p4_titulo: "Transfer summary",
                res_tipo: "Type",
                res_debitar: "Amount to debit",
                res_acreditar: "Amount to credit",
                sin_saldo_moneda: "No balance in {{moneda}}. {{monto}} will be used from your BOB balance.",
                bob_necesarios: "BOB needed",
                bob_disponibles: "BOB available",
                destino_recibira: "Destination will receive",
                procesando: "Processing…",
                confirmar: "✓ Confirm transfer",
                confirmar_conversion: "✓ Confirm with BOB conversion",
                cancelar: "Cancel",
                exito_titulo: "Transfer successful!",
                exito_debitado: "Amount debited",
                exito_acreditado: "Amount credited",
                exito_tasa: "Applied rate",
                otra_transferencia: "Make another transfer",
                continuar: "Continue →",
                atras: "← Back",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Brazilian Real", mon_ARS: "Argentine Peso",
                mon_CLP: "Chilean Peso", mon_PEN: "Peruvian Sol", mon_COP: "Colombian Peso",
            },
            login: {
                titulo: "Sign in", correo: "Email address", contrasena: "Password",
                verificando: "Verifying...", iniciar: "Sign in",
                quiero: "I want to", registrarme: "Register",
                error_credenciales: "Incorrect credentials",
            },
            reg: {
                paso_correo: "Email", paso_verificar: "Verify", paso_datos: "Details",
                paso_cuenta: "Account", paso_confirmar: "Confirm",
                p0_titulo: "Create your account", p0_sub: "Enter your email to get started. We'll send you a verification code.",
                correo_label: "Email address",
                enviando: "Sending code…", enviar_codigo: "Send verification code →",
                codigo_enviado_a: "Code sent to",
                tengo_codigo: "I have my code →",
                p1_titulo: "Verify your email", p1_sub: "Enter the 6-digit code we sent to your email.",
                codigo_label: "Verification code",
                verificando: "Verifying…", verificar: "Verify →",
                no_recibiste: "Didn't receive the code?", reenviar: "Resend",
                p2_titulo: "Personal details", p2_sub: "Fill in your information to create the account.",
                nombre: "First name", apellido: "Last name", telefono: "Phone",
                edad: "Age", direccion: "Address", contrasena: "Password",
                contrasena_placeholder: "Minimum 8 characters",
                p3_titulo: "Account and card type", p3_sub: "Choose the options that best suit you.",
                tipo_cuenta_label: "Account type", tipo_tarjeta_label: "Card type",
                cuenta_ahorro: "Savings", cuenta_ahorro_desc: "Ideal for saving money",
                cuenta_corriente: "Checking", cuenta_corriente_desc: "For daily use and transactions",
                tarjeta_debito: "Debit", tarjeta_debito_desc: "Spend only what you have",
                tarjeta_credito: "Credit", tarjeta_credito_desc: "Buy now and pay later",
                p4_titulo: "Confirm registration", p4_sub: "Review your details before creating the account.",
                anios: "years old", registrando: "Registering…", crear_cuenta: "✓ Create account",
                exito_titulo: "Account created!", exito_msg: "Your account was registered successfully.",
                exito_correo_aviso: "We sent your card number, account number and PIN to:",
                exito_redireccion: "Check your inbox (and spam). You'll be redirected automatically in a few seconds...",
                ir_login: "Go to Login now",
                error_crear: "An error occurred creating the account",
                atras: "Back", continuar: "Continue →",
            },
            lang: { titulo: "Language" },
        },
    },

    // ── PORTUGUÊS ─────────────────────────────────────────────────────────────
    pt: {
        translation: {
            nav: {
                buscar: "Pesquisar", inicio: "Início", actividad: "Atividade",
                retirar: "Sacar Dinheiro", depositar: "Depositar Dinheiro",
                transferir: "Transferir Dinheiro", ayuda: "Ajuda",
            },
            cli: {
                cargando: "Carregando dados...",
                sin_sesion: "Nenhum usuário encontrado na sessão.",
                sin_nombre: "Nenhum nome de usuário encontrado na sessão.",
                error_carga: "Erro ao carregar os dados do usuário.",
                cuenta: "Conta", mostrar_datos: "Mostrar dados", ocultar_datos: "Ocultar dados",
                numero: "Número", saldo: "Saldo", estado: "Status",
                titular: "Titular", vence: "Vence", tipo: "Tipo",
                ultimas_transacciones: "Últimas transações",
                sin_transacciones: "Nenhuma transação registrada.",
                col_fecha: "Data", col_tipo: "Tipo", col_metodo: "Método",
                col_monto: "Valor", col_descripcion: "Descrição",
                col_destinatario: "Destinatário", col_estado: "Status",
            },
            act: {
                cargando: "Carregando atividade…", sin_sesion: "Nenhuma sessão ativa.",
                total_depositos: "Total de Depósitos", total_retiros: "Total de Saques",
                transferencias: "Transferências", balance_neto: "Saldo Líquido",
                csv: "CSV", pdf: "PDF", exportando: "Exportando…",
                sin_datos_exportar: "Sem dados para exportar.", error_exportar: "Erro ao exportar.",
                actividad_mensual: "Atividade Mensal", barras: "Barras",
                linea: "Linha", distribucion: "Distribuição",
                depositos: "Depósitos", retiros: "Saques",
                buscar_placeholder: "Pesquisar (Netflix, supermercado…)",
                todos_tipos: "Todos os tipos", todas_cuentas: "Todas as contas",
                filtrar: "Filtrar", limpiar: "Limpar",
                filtros_activos: "Filtros ativos — {{count}} resultado(s)",
                transacciones_tab: "Transações", cuentas_tab: "Contas Vinculadas",
                col_id: "#", col_fecha: "Data", col_tipo: "Tipo", col_metodo: "Método",
                col_monto: "Valor", col_saldo_post: "Saldo Pós.",
                col_descripcion: "Descrição", col_destinatario: "Destinatário", col_estado: "Status",
                sin_transacciones: "Sem transações para os filtros selecionados.",
                pg_info: "{{actual}}/{{total}} · {{count}} transações",
                principal: "Principal", sin_saldo: "Sem saldo registrado",
                vence: "vence", tipo_cuenta_label: "Posição",
            },
            dep: {
                cargando_sesion: "Carregando dados da sessão…",
                sin_sesion: "Nenhuma sessão ativa encontrada.",
                error_sesion: "Erro ao carregar dados da sessão.",
                paso_tipo: "Tipo", paso_monedas: "Moedas", paso_monto: "Valor",
                paso_seguridad: "Segurança", paso_confirmar: "Confirmar",
                p0_titulo: "Que tipo de depósito você deseja realizar?",
                tipo_directo: "Depósito Direto",
                tipo_directo_desc: "Credita na mesma moeda que você entrega",
                tipo_conversion: "Depósito com Conversão",
                tipo_conversion_desc: "Converte para outra moeda ao creditar",
                p1_titulo: "Moeda e valor",
                moneda_entrega: "Moeda que você entrega", moneda_acreditar: "Moeda a creditar",
                tipo_tasa: "Tipo de taxa", metodo_deposito: "Método de depósito",
                monto_label: "Valor a depositar",
                preview_recibiras: "Você receberá", preview_en_cuenta: "na sua conta.",
                cargando_tasas: "Carregando taxas…", equiv_bob: "Equivalente em BOB",
                recibiras_en: "Você receberá em", tasa_label: "Taxa",
                p2_titulo: "Verificação de segurança",
                p2_sub: "Insira sua senha e PIN para confirmar",
                cuenta_label: "Conta", tarjeta_label: "Cartão",
                contrasena: "Senha", pin: "PIN do cartão",
                p3_titulo: "Resumo do depósito",
                res_tipo: "Tipo", res_entregas: "Você entrega", res_acredita: "Creditado como",
                res_metodo: "Método", res_correo: "E-mail",
                procesando: "Processando…", confirmar: "✓ Confirmar depósito",
                exito_titulo: "Depósito realizado!", exito_recibido: "Valor recebido",
                exito_acreditado: "Valor creditado", exito_tasa: "Taxa aplicada",
                otro_deposito: "Fazer outro depósito",
                continuar: "Continuar →", atras: "← Voltar",
                mon_BOB: "Boliviano", mon_USD: "Dólar", mon_EUR: "Euro",
                mon_BRL: "Real Brasileiro", mon_ARS: "Peso Argentino",
                mon_CLP: "Peso Chileno", mon_PEN: "Sol Peruano", mon_COP: "Peso Colombiano",
            },
            ret: {
                paso_datos: "Dados", paso_moneda: "Moeda",
                paso_confirmar: "Confirmar", paso_listo: "Concluído",
                f0_titulo: "Quanto você quer sacar?",
                autenticacion: "Autenticação",
                num_tarjeta: "Número do cartão",
                pin: "PIN",
                ver_opciones: "Ver opções →",
                f1_titulo: "Em qual moeda você saca?",
                f1_sub_inicio: "Saque de",
                f1_sub_fin: "escolha como deseja receber o dinheiro",
                recibes: "Você recebe",
                disponible: "Disponível",
                sin_saldo: "Sem saldo",
                saldo_insuf_title: "Saldo insuficiente nesta moeda",
                cambiar_monto: "← Alterar valor",
                f2_titulo: "Confirmar conversão",
                f2_sub_ini: "Você não tem saldo em",
                f2_sub_fin: "Será convertido do seu saldo em BOB.",
                conv_retiras: "Você saca",
                conv_bob: "BOB a descontar",
                conv_saldo_bob: "Saldo BOB atual",
                cambiar_moneda: "← Alterar moeda",
                confirmar_retiro: "✓ Confirmar saque",
                exito_titulo: "Saque realizado!",
                res_solicitado: "Solicitado",
                res_entregado: "Entregue",
                res_bob_desc: "BOB descontados",
                res_equiv_bob: "Equiv. BOB",
                res_tasa: "Taxa aplicada",
                otro_retiro: "Fazer outro saque",
                error_retiro: "Não foi possível concluir o saque.",
            },
            trf: {
                cargando_sesion: "Carregando dados da sessão…",
                sin_sesion: "Nenhuma sessão ativa encontrada.",
                error_sesion: "Erro ao carregar dados da sessão.",
                paso_tipo: "Tipo", paso_cuentas: "Contas", paso_monto: "Valor",
                paso_seguridad: "Segurança", paso_confirmar: "Confirmar",
                p0_titulo: "Que tipo de transferência você deseja realizar?",
                tipo_directa: "Transferência Direta",
                tipo_directa_desc: "Transfere na mesma moeda",
                tipo_conversion: "Transferência com Conversão",
                tipo_conversion_desc: "Converte a moeda ao transferir",
                p1_titulo: "Contas de origem e destino",
                cuenta_origen: "Conta origem",
                cuenta_origen_hint: "Sua conta ativa",
                cuenta_destino: "Conta destino",
                cuenta_destino_placeholder: "Número da conta destino",
                descripcion: "Descrição (opcional)",
                descripcion_placeholder: "Ex: Pagamento de dívida, aluguel…",
                misma_cuenta_warn: "A conta origem e destino não podem ser iguais.",
                p2_titulo: "Valor e moeda",
                moneda_debitar: "Moeda a debitar",
                moneda_acreditar: "Moeda a creditar",
                disponible: "Disponível",
                tipo_tasa: "Tipo de taxa",
                metodo: "Método",
                monto_label: "Valor a transferir",
                preview_recibira: "O destinatário receberá",
                cargando_tasas: "Carregando taxas…",
                equiv_bob: "Equivalente em BOB",
                recibira_en: "Receberá em",
                tasa_label: "Taxa",
                p3_titulo: "Verifique os dados",
                p3_sub: "Confirme que os dados estão corretos antes de continuar",
                p4_titulo: "Resumo da transferência",
                res_tipo: "Tipo",
                res_debitar: "Valor a debitar",
                res_acreditar: "Valor a creditar",
                sin_saldo_moneda: "Sem saldo em {{moneda}}. {{monto}} serão usados do seu saldo em BOB.",
                bob_necesarios: "BOB necessários",
                bob_disponibles: "BOB disponíveis",
                destino_recibira: "O destino receberá",
                procesando: "Processando…",
                confirmar: "✓ Confirmar transferência",
                confirmar_conversion: "✓ Confirmar com conversão BOB",
                cancelar: "Cancelar",
                exito_titulo: "Transferência realizada!",
                exito_debitado: "Valor debitado",
                exito_acreditado: "Valor creditado",
                exito_tasa: "Taxa aplicada",
                otra_transferencia: "Fazer outra transferência",
                continuar: "Continuar →",
                atras: "← Voltar",
                mon_BOB: "Boliviano", mon_USD: "Dólar", mon_EUR: "Euro",
                mon_BRL: "Real Brasileiro", mon_ARS: "Peso Argentino",
                mon_CLP: "Peso Chileno", mon_PEN: "Sol Peruano", mon_COP: "Peso Colombiano",
            },
            login: {
                titulo: "Entrar", correo: "Endereço de e-mail", contrasena: "Senha",
                verificando: "Verificando...", iniciar: "Entrar",
                quiero: "Quero", registrarme: "Registrar-me",
                error_credenciales: "Credenciais incorretas",
            },
            reg: {
                paso_correo: "E-mail", paso_verificar: "Verificar", paso_datos: "Dados",
                paso_cuenta: "Conta", paso_confirmar: "Confirmar",
                p0_titulo: "Crie sua conta", p0_sub: "Digite seu e-mail para começar. Enviaremos um código de verificação.",
                correo_label: "Endereço de e-mail",
                enviando: "Enviando código…", enviar_codigo: "Enviar código de verificação →",
                codigo_enviado_a: "Código enviado para",
                tengo_codigo: "Tenho meu código →",
                p1_titulo: "Verifique seu e-mail", p1_sub: "Digite o código de 6 dígitos que enviamos para seu e-mail.",
                codigo_label: "Código de verificação",
                verificando: "Verificando…", verificar: "Verificar →",
                no_recibiste: "Não recebeu o código?", reenviar: "Reenviar",
                p2_titulo: "Dados pessoais", p2_sub: "Preencha suas informações para criar a conta.",
                nombre: "Nome", apellido: "Sobrenome", telefono: "Telefone",
                edad: "Idade", direccion: "Endereço", contrasena: "Senha",
                contrasena_placeholder: "Mínimo 8 caracteres",
                p3_titulo: "Tipo de conta e cartão", p3_sub: "Escolha as opções que melhor se adaptam a você.",
                tipo_cuenta_label: "Tipo de conta", tipo_tarjeta_label: "Tipo de cartão",
                cuenta_ahorro: "Poupança", cuenta_ahorro_desc: "Ideal para guardar e economizar",
                cuenta_corriente: "Corrente", cuenta_corriente_desc: "Para uso diário e transações",
                tarjeta_debito: "Débito", tarjeta_debito_desc: "Gaste apenas o que você tem",
                tarjeta_credito: "Crédito", tarjeta_credito_desc: "Compre agora e pague depois",
                p4_titulo: "Confirmar registro", p4_sub: "Revise seus dados antes de criar a conta.",
                anios: "anos", registrando: "Registrando…", crear_cuenta: "✓ Criar conta",
                exito_titulo: "Conta criada!", exito_msg: "Sua conta foi registrada com sucesso.",
                exito_correo_aviso: "Enviamos seu número de cartão, número de conta e PIN para:",
                exito_redireccion: "Verifique sua caixa de entrada (e spam). Você será redirecionado automaticamente em alguns segundos...",
                ir_login: "Ir para o Login agora",
                error_crear: "Ocorreu um erro ao criar a conta",
                atras: "Voltar", continuar: "Continuar →",
            },
            lang: { titulo: "Idioma" },
        },
    },

    // ── FRANÇAIS ──────────────────────────────────────────────────────────────
    fr: {
        translation: {
            nav: {
                buscar: "Rechercher", inicio: "Accueil", actividad: "Activité",
                retirar: "Retirer de l'argent", depositar: "Déposer de l'argent",
                transferir: "Virer de l'argent", ayuda: "Aide",
            },
            cli: {
                cargando: "Chargement des données...",
                sin_sesion: "Aucun utilisateur trouvé en session.",
                sin_nombre: "Aucun nom d'utilisateur trouvé en session.",
                error_carga: "Erreur lors du chargement des données.",
                cuenta: "Compte", mostrar_datos: "Afficher les données", ocultar_datos: "Masquer les données",
                numero: "Numéro", saldo: "Solde", estado: "Statut",
                titular: "Titulaire", vence: "Expire", tipo: "Type",
                ultimas_transacciones: "Dernières transactions",
                sin_transacciones: "Aucune transaction enregistrée.",
                col_fecha: "Date", col_tipo: "Type", col_metodo: "Méthode",
                col_monto: "Montant", col_descripcion: "Description",
                col_destinatario: "Destinataire", col_estado: "Statut",
            },
            act: {
                cargando: "Chargement de l'activité…", sin_sesion: "Aucune session active.",
                total_depositos: "Total des Dépôts", total_retiros: "Total des Retraits",
                transferencias: "Virements", balance_neto: "Solde Net",
                csv: "CSV", pdf: "PDF", exportando: "Exportation…",
                sin_datos_exportar: "Aucune donnée à exporter.", error_exportar: "Erreur d'exportation.",
                actividad_mensual: "Activité Mensuelle", barras: "Barres",
                linea: "Ligne", distribucion: "Distribution",
                depositos: "Dépôts", retiros: "Retraits",
                buscar_placeholder: "Rechercher (Netflix, supermarché…)",
                todos_tipos: "Tous les types", todas_cuentas: "Tous les comptes",
                filtrar: "Filtrer", limpiar: "Effacer",
                filtros_activos: "Filtres actifs — {{count}} résultat(s)",
                transacciones_tab: "Transactions", cuentas_tab: "Comptes Liés",
                col_id: "#", col_fecha: "Date", col_tipo: "Type", col_metodo: "Méthode",
                col_monto: "Montant", col_saldo_post: "Solde Post.",
                col_descripcion: "Description", col_destinatario: "Destinataire", col_estado: "Statut",
                sin_transacciones: "Aucune transaction pour les filtres sélectionnés.",
                pg_info: "{{actual}}/{{total}} · {{count}} transactions",
                principal: "Principal", sin_saldo: "Aucun solde enregistré",
                vence: "expire le", tipo_cuenta_label: "Position",
            },
            dep: {
                cargando_sesion: "Chargement des données de session…",
                sin_sesion: "Aucune session active trouvée.",
                error_sesion: "Erreur lors du chargement de la session.",
                paso_tipo: "Type", paso_monedas: "Devises", paso_monto: "Montant",
                paso_seguridad: "Sécurité", paso_confirmar: "Confirmer",
                p0_titulo: "Quel type de dépôt souhaitez-vous effectuer ?",
                tipo_directo: "Dépôt Direct",
                tipo_directo_desc: "Crédité dans la même devise que vous fournissez",
                tipo_conversion: "Dépôt avec Conversion",
                tipo_conversion_desc: "Convertit dans une autre devise au crédit",
                p1_titulo: "Devise et montant",
                moneda_entrega: "Devise que vous fournissez", moneda_acreditar: "Devise à créditer",
                tipo_tasa: "Type de taux", metodo_deposito: "Méthode de dépôt",
                monto_label: "Montant à déposer",
                preview_recibiras: "Vous recevrez", preview_en_cuenta: "sur votre compte.",
                cargando_tasas: "Chargement des taux…", equiv_bob: "Équivalent en BOB",
                recibiras_en: "Vous recevrez en", tasa_label: "Taux",
                p2_titulo: "Vérification de sécurité",
                p2_sub: "Saisissez votre mot de passe et PIN pour confirmer",
                cuenta_label: "Compte", tarjeta_label: "Carte",
                contrasena: "Mot de passe", pin: "PIN de la carte",
                p3_titulo: "Récapitulatif du dépôt",
                res_tipo: "Type", res_entregas: "Vous fournissez", res_acredita: "Crédité en",
                res_metodo: "Méthode", res_correo: "E-mail",
                procesando: "Traitement…", confirmar: "✓ Confirmer le dépôt",
                exito_titulo: "Dépôt réussi !", exito_recibido: "Montant reçu",
                exito_acreditado: "Montant crédité", exito_tasa: "Taux appliqué",
                otro_deposito: "Faire un autre dépôt",
                continuar: "Continuer →", atras: "← Retour",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Réal Brésilien", mon_ARS: "Peso Argentin",
                mon_CLP: "Peso Chilien", mon_PEN: "Sol Péruvien", mon_COP: "Peso Colombien",
            },
            ret: {
                paso_datos: "Données", paso_moneda: "Devise",
                paso_confirmar: "Confirmer", paso_listo: "Terminé",
                f0_titulo: "Combien souhaitez-vous retirer ?",
                autenticacion: "Authentification",
                num_tarjeta: "Numéro de carte",
                pin: "PIN",
                ver_opciones: "Voir les options →",
                f1_titulo: "Dans quelle devise retirez-vous ?",
                f1_sub_inicio: "Retrait de",
                f1_sub_fin: "choisissez comment vous souhaitez recevoir l'argent",
                recibes: "Vous recevez",
                disponible: "Disponible",
                sin_saldo: "Sans solde",
                saldo_insuf_title: "Solde insuffisant dans cette devise",
                cambiar_monto: "← Modifier le montant",
                f2_titulo: "Confirmer la conversion",
                f2_sub_ini: "Vous n'avez pas de solde en",
                f2_sub_fin: "Il sera converti depuis votre solde en BOB.",
                conv_retiras: "Vous retirez",
                conv_bob: "BOB à déduire",
                conv_saldo_bob: "Solde BOB actuel",
                cambiar_moneda: "← Changer de devise",
                confirmar_retiro: "✓ Confirmer le retrait",
                exito_titulo: "Retrait réussi !",
                res_solicitado: "Demandé",
                res_entregado: "Remis",
                res_bob_desc: "BOB déduits",
                res_equiv_bob: "Équiv. BOB",
                res_tasa: "Taux appliqué",
                otro_retiro: "Effectuer un autre retrait",
                error_retiro: "Impossible de finaliser le retrait.",
            },
            trf: {
                cargando_sesion: "Chargement des données de session…",
                sin_sesion: "Aucune session active trouvée.",
                error_sesion: "Erreur lors du chargement de la session.",
                paso_tipo: "Type", paso_cuentas: "Comptes", paso_monto: "Montant",
                paso_seguridad: "Sécurité", paso_confirmar: "Confirmer",
                p0_titulo: "Quel type de virement souhaitez-vous effectuer ?",
                tipo_directa: "Virement Direct",
                tipo_directa_desc: "Vire dans la même devise",
                tipo_conversion: "Virement avec Conversion",
                tipo_conversion_desc: "Convertit la devise lors du virement",
                p1_titulo: "Comptes source et destinataire",
                cuenta_origen: "Compte source",
                cuenta_origen_hint: "Votre compte actif",
                cuenta_destino: "Compte destinataire",
                cuenta_destino_placeholder: "Numéro du compte destinataire",
                descripcion: "Description (optionnelle)",
                descripcion_placeholder: "Ex : Remboursement, loyer…",
                misma_cuenta_warn: "Le compte source et le compte destinataire ne peuvent pas être identiques.",
                p2_titulo: "Montant et devise",
                moneda_debitar: "Devise à débiter",
                moneda_acreditar: "Devise à créditer",
                disponible: "Disponible",
                tipo_tasa: "Type de taux",
                metodo: "Méthode",
                monto_label: "Montant à virer",
                preview_recibira: "Le destinataire recevra",
                cargando_tasas: "Chargement des taux…",
                equiv_bob: "Équivalent en BOB",
                recibira_en: "Recevra en",
                tasa_label: "Taux",
                p3_titulo: "Vérifier les informations",
                p3_sub: "Vérifiez que les informations sont correctes avant de continuer",
                p4_titulo: "Récapitulatif du virement",
                res_tipo: "Type",
                res_debitar: "Montant à débiter",
                res_acreditar: "Montant à créditer",
                sin_saldo_moneda: "Pas de solde en {{moneda}}. {{monto}} seront prélevés depuis votre solde en BOB.",
                bob_necesarios: "BOB nécessaires",
                bob_disponibles: "BOB disponibles",
                destino_recibira: "Le destinataire recevra",
                procesando: "Traitement…",
                confirmar: "✓ Confirmer le virement",
                confirmar_conversion: "✓ Confirmer avec conversion BOB",
                cancelar: "Annuler",
                exito_titulo: "Virement réussi !",
                exito_debitado: "Montant débité",
                exito_acreditado: "Montant crédité",
                exito_tasa: "Taux appliqué",
                otra_transferencia: "Effectuer un autre virement",
                continuar: "Continuer →",
                atras: "← Retour",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Réal Brésilien", mon_ARS: "Peso Argentin",
                mon_CLP: "Peso Chilien", mon_PEN: "Sol Péruvien", mon_COP: "Peso Colombien",
            },
            login: {
                titulo: "Connexion", correo: "Adresse e-mail", contrasena: "Mot de passe",
                verificando: "Vérification...", iniciar: "Se connecter",
                quiero: "Je veux", registrarme: "M'inscrire",
                error_credenciales: "Identifiants incorrects",
            },
            reg: {
                paso_correo: "E-mail", paso_verificar: "Vérifier", paso_datos: "Données",
                paso_cuenta: "Compte", paso_confirmar: "Confirmer",
                p0_titulo: "Créez votre compte", p0_sub: "Entrez votre e-mail pour commencer. Nous vous enverrons un code de vérification.",
                correo_label: "Adresse e-mail",
                enviando: "Envoi du code…", enviar_codigo: "Envoyer le code de vérification →",
                codigo_enviado_a: "Code envoyé à",
                tengo_codigo: "J'ai mon code →",
                p1_titulo: "Vérifiez votre e-mail", p1_sub: "Entrez le code à 6 chiffres que nous avons envoyé à votre e-mail.",
                codigo_label: "Code de vérification",
                verificando: "Vérification…", verificar: "Vérifier →",
                no_recibiste: "Vous n'avez pas reçu le code ?", reenviar: "Renvoyer",
                p2_titulo: "Données personnelles", p2_sub: "Complétez vos informations pour créer le compte.",
                nombre: "Prénom", apellido: "Nom", telefono: "Téléphone",
                edad: "Âge", direccion: "Adresse", contrasena: "Mot de passe",
                contrasena_placeholder: "Minimum 8 caractères",
                p3_titulo: "Type de compte et carte", p3_sub: "Choisissez les options qui vous conviennent le mieux.",
                tipo_cuenta_label: "Type de compte", tipo_tarjeta_label: "Type de carte",
                cuenta_ahorro: "Épargne", cuenta_ahorro_desc: "Idéal pour économiser",
                cuenta_corriente: "Courant", cuenta_corriente_desc: "Pour un usage quotidien et les transactions",
                tarjeta_debito: "Débit", tarjeta_debito_desc: "Dépensez seulement ce que vous avez",
                tarjeta_credito: "Crédit", tarjeta_credito_desc: "Achetez maintenant et payez plus tard",
                p4_titulo: "Confirmer l'inscription", p4_sub: "Vérifiez vos données avant de créer le compte.",
                anios: "ans", registrando: "Inscription…", crear_cuenta: "✓ Créer le compte",
                exito_titulo: "Compte créé !", exito_msg: "Votre compte a été enregistré avec succès.",
                exito_correo_aviso: "Nous avons envoyé votre numéro de carte, numéro de compte et PIN à :",
                exito_redireccion: "Vérifiez votre boîte de réception (et spam). Vous serez redirigé automatiquement dans quelques secondes...",
                ir_login: "Aller à la connexion maintenant",
                error_crear: "Une erreur s'est produite lors de la création du compte",
                atras: "Retour", continuar: "Continuer →",
            },
            lang: { titulo: "Langue" },
        },
    },

    // ── DEUTSCH ───────────────────────────────────────────────────────────────
    de: {
        translation: {
            nav: {
                buscar: "Suchen", inicio: "Startseite", actividad: "Aktivität",
                retirar: "Geld abheben", depositar: "Geld einzahlen",
                transferir: "Geld überweisen", ayuda: "Hilfe",
            },
            cli: {
                cargando: "Daten werden geladen...",
                sin_sesion: "Kein Benutzer in der Sitzung gefunden.",
                sin_nombre: "Kein Benutzername in der Sitzung gefunden.",
                error_carga: "Fehler beim Laden der Benutzerdaten.",
                cuenta: "Konto", mostrar_datos: "Daten anzeigen", ocultar_datos: "Daten ausblenden",
                numero: "Nummer", saldo: "Guthaben", estado: "Status",
                titular: "Inhaber", vence: "Läuft ab", tipo: "Typ",
                ultimas_transacciones: "Letzte Transaktionen",
                sin_transacciones: "Keine Transaktionen erfasst.",
                col_fecha: "Datum", col_tipo: "Typ", col_metodo: "Methode",
                col_monto: "Betrag", col_descripcion: "Beschreibung",
                col_destinatario: "Empfänger", col_estado: "Status",
            },
            act: {
                cargando: "Aktivität wird geladen…", sin_sesion: "Keine aktive Sitzung.",
                total_depositos: "Gesamte Einzahlungen", total_retiros: "Gesamte Abhebungen",
                transferencias: "Überweisungen", balance_neto: "Nettoguthaben",
                csv: "CSV", pdf: "PDF", exportando: "Exportieren…",
                sin_datos_exportar: "Keine Daten zum Exportieren.", error_exportar: "Exportfehler.",
                actividad_mensual: "Monatliche Aktivität", barras: "Balken",
                linea: "Linie", distribucion: "Verteilung",
                depositos: "Einzahlungen", retiros: "Abhebungen",
                buscar_placeholder: "Suchen (Netflix, Supermarkt…)",
                todos_tipos: "Alle Typen", todas_cuentas: "Alle Konten",
                filtrar: "Filtern", limpiar: "Löschen",
                filtros_activos: "Aktive Filter — {{count}} Ergebnis(se)",
                transacciones_tab: "Transaktionen", cuentas_tab: "Verknüpfte Konten",
                col_id: "#", col_fecha: "Datum", col_tipo: "Typ", col_metodo: "Methode",
                col_monto: "Betrag", col_saldo_post: "Nachguthaben",
                col_descripcion: "Beschreibung", col_destinatario: "Empfänger", col_estado: "Status",
                sin_transacciones: "Keine Transaktionen für die ausgewählten Filter.",
                pg_info: "{{actual}}/{{total}} · {{count}} Transaktionen",
                principal: "Haupt", sin_saldo: "Kein Guthaben erfasst",
                vence: "läuft ab", tipo_cuenta_label: "Position",
            },
            dep: {
                cargando_sesion: "Sitzungsdaten werden geladen…",
                sin_sesion: "Keine aktive Sitzung gefunden.",
                error_sesion: "Fehler beim Laden der Sitzungsdaten.",
                paso_tipo: "Typ", paso_monedas: "Währungen", paso_monto: "Betrag",
                paso_seguridad: "Sicherheit", paso_confirmar: "Bestätigen",
                p0_titulo: "Welche Art von Einzahlung möchten Sie vornehmen?",
                tipo_directo: "Direkte Einzahlung",
                tipo_directo_desc: "Wird in der gleichen Währung gutgeschrieben",
                tipo_conversion: "Einzahlung mit Umrechnung",
                tipo_conversion_desc: "Wird in eine andere Währung umgerechnet",
                p1_titulo: "Währung und Betrag",
                moneda_entrega: "Währung, die Sie einzahlen", moneda_acreditar: "Gutzuschreibende Währung",
                tipo_tasa: "Kurstyp", metodo_deposito: "Einzahlungsmethode",
                monto_label: "Einzuzahlender Betrag",
                preview_recibiras: "Sie erhalten", preview_en_cuenta: "auf Ihrem Konto.",
                cargando_tasas: "Kurse werden geladen…", equiv_bob: "Äquivalent in BOB",
                recibiras_en: "Sie erhalten in", tasa_label: "Kurs",
                p2_titulo: "Sicherheitsverifizierung",
                p2_sub: "Geben Sie Ihr Passwort und Ihren PIN zur Bestätigung ein",
                cuenta_label: "Konto", tarjeta_label: "Karte",
                contrasena: "Passwort", pin: "Karten-PIN",
                p3_titulo: "Einzahlungsübersicht",
                res_tipo: "Typ", res_entregas: "Sie zahlen ein", res_acredita: "Gutgeschrieben als",
                res_metodo: "Methode", res_correo: "E-Mail",
                procesando: "Verarbeitung…", confirmar: "✓ Einzahlung bestätigen",
                exito_titulo: "Einzahlung erfolgreich!", exito_recibido: "Erhaltener Betrag",
                exito_acreditado: "Gutgeschriebener Betrag", exito_tasa: "Angewandter Kurs",
                otro_deposito: "Weitere Einzahlung vornehmen",
                continuar: "Weiter →", atras: "← Zurück",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Brasilianischer Real", mon_ARS: "Argentinischer Peso",
                mon_CLP: "Chilenischer Peso", mon_PEN: "Peruanischer Sol", mon_COP: "Kolumbianischer Peso",
            },
            ret: {
                paso_datos: "Daten", paso_moneda: "Währung",
                paso_confirmar: "Bestätigen", paso_listo: "Fertig",
                f0_titulo: "Wie viel möchten Sie abheben?",
                autenticacion: "Authentifizierung",
                num_tarjeta: "Kartennummer",
                pin: "PIN",
                ver_opciones: "Optionen ansehen →",
                f1_titulo: "In welcher Währung heben Sie ab?",
                f1_sub_inicio: "Abhebung von",
                f1_sub_fin: "wählen Sie, wie Sie das Geld erhalten möchten",
                recibes: "Sie erhalten",
                disponible: "Verfügbar",
                sin_saldo: "Kein Guthaben",
                saldo_insuf_title: "Unzureichendes Guthaben in dieser Währung",
                cambiar_monto: "← Betrag ändern",
                f2_titulo: "Umrechnung bestätigen",
                f2_sub_ini: "Sie haben kein Guthaben in",
                f2_sub_fin: "Es wird aus Ihrem BOB-Guthaben umgerechnet.",
                conv_retiras: "Sie heben ab",
                conv_bob: "BOB abzubuchen",
                conv_saldo_bob: "Aktuelles BOB-Guthaben",
                cambiar_moneda: "← Währung ändern",
                confirmar_retiro: "✓ Abhebung bestätigen",
                exito_titulo: "Abhebung erfolgreich!",
                res_solicitado: "Angefordert",
                res_entregado: "Ausgezahlt",
                res_bob_desc: "BOB abgebucht",
                res_equiv_bob: "BOB-Äquiv.",
                res_tasa: "Angewandter Kurs",
                otro_retiro: "Weitere Abhebung vornehmen",
                error_retiro: "Die Abhebung konnte nicht abgeschlossen werden.",
            },
            trf: {
                cargando_sesion: "Sitzungsdaten werden geladen…",
                sin_sesion: "Keine aktive Sitzung gefunden.",
                error_sesion: "Fehler beim Laden der Sitzungsdaten.",
                paso_tipo: "Typ", paso_cuentas: "Konten", paso_monto: "Betrag",
                paso_seguridad: "Sicherheit", paso_confirmar: "Bestätigen",
                p0_titulo: "Welche Art von Überweisung möchten Sie vornehmen?",
                tipo_directa: "Direktüberweisung",
                tipo_directa_desc: "Überweist in der gleichen Währung",
                tipo_conversion: "Überweisung mit Umrechnung",
                tipo_conversion_desc: "Rechnet die Währung beim Überweisen um",
                p1_titulo: "Quell- und Zielkonto",
                cuenta_origen: "Quellkonto",
                cuenta_origen_hint: "Ihr aktives Konto",
                cuenta_destino: "Zielkonto",
                cuenta_destino_placeholder: "Zielkontonummer",
                descripcion: "Beschreibung (optional)",
                descripcion_placeholder: "Z.B.: Schuldenrückzahlung, Miete…",
                misma_cuenta_warn: "Quell- und Zielkonto können nicht identisch sein.",
                p2_titulo: "Betrag und Währung",
                moneda_debitar: "Abzubuchende Währung",
                moneda_acreditar: "Gutzuschreibende Währung",
                disponible: "Verfügbar",
                tipo_tasa: "Kurstyp",
                metodo: "Methode",
                monto_label: "Überweisungsbetrag",
                preview_recibira: "Der Empfänger erhält",
                cargando_tasas: "Kurse werden geladen…",
                equiv_bob: "Äquivalent in BOB",
                recibira_en: "Erhält in",
                tasa_label: "Kurs",
                p3_titulo: "Daten überprüfen",
                p3_sub: "Überprüfen Sie die Daten, bevor Sie fortfahren",
                p4_titulo: "Überweisungsübersicht",
                res_tipo: "Typ",
                res_debitar: "Abzubuchender Betrag",
                res_acreditar: "Gutzuschreibender Betrag",
                sin_saldo_moneda: "Kein Guthaben in {{moneda}}. {{monto}} werden aus Ihrem BOB-Guthaben abgebucht.",
                bob_necesarios: "BOB benötigt",
                bob_disponibles: "BOB verfügbar",
                destino_recibira: "Ziel erhält",
                procesando: "Verarbeitung…",
                confirmar: "✓ Überweisung bestätigen",
                confirmar_conversion: "✓ Mit BOB-Umrechnung bestätigen",
                cancelar: "Abbrechen",
                exito_titulo: "Überweisung erfolgreich!",
                exito_debitado: "Abgebuchter Betrag",
                exito_acreditado: "Gutgeschriebener Betrag",
                exito_tasa: "Angewandter Kurs",
                otra_transferencia: "Weitere Überweisung vornehmen",
                continuar: "Weiter →",
                atras: "← Zurück",
                mon_BOB: "Boliviano", mon_USD: "Dollar", mon_EUR: "Euro",
                mon_BRL: "Brasilianischer Real", mon_ARS: "Argentinischer Peso",
                mon_CLP: "Chilenischer Peso", mon_PEN: "Peruanischer Sol", mon_COP: "Kolumbianischer Peso",
            },
            login: {
                titulo: "Anmelden", correo: "E-Mail-Adresse", contrasena: "Passwort",
                verificando: "Überprüfung...", iniciar: "Anmelden",
                quiero: "Ich möchte mich", registrarme: "Registrieren",
                error_credenciales: "Falsche Anmeldedaten",
            },
            reg: {
                paso_correo: "E-Mail", paso_verificar: "Verifizieren", paso_datos: "Daten",
                paso_cuenta: "Konto", paso_confirmar: "Bestätigen",
                p0_titulo: "Konto erstellen", p0_sub: "Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Bestätigungscode.",
                correo_label: "E-Mail-Adresse",
                enviando: "Code wird gesendet…", enviar_codigo: "Bestätigungscode senden →",
                codigo_enviado_a: "Code gesendet an",
                tengo_codigo: "Ich habe meinen Code →",
                p1_titulo: "E-Mail verifizieren", p1_sub: "Geben Sie den 6-stelligen Code ein, den wir an Ihre E-Mail gesendet haben.",
                codigo_label: "Bestätigungscode",
                verificando: "Verifizierung…", verificar: "Verifizieren →",
                no_recibiste: "Code nicht erhalten?", reenviar: "Erneut senden",
                p2_titulo: "Persönliche Daten", p2_sub: "Füllen Sie Ihre Angaben aus, um das Konto zu erstellen.",
                nombre: "Vorname", apellido: "Nachname", telefono: "Telefon",
                edad: "Alter", direccion: "Adresse", contrasena: "Passwort",
                contrasena_placeholder: "Mindestens 8 Zeichen",
                p3_titulo: "Konto- und Kartentyp", p3_sub: "Wählen Sie die Optionen, die am besten zu Ihnen passen.",
                tipo_cuenta_label: "Kontotyp", tipo_tarjeta_label: "Kartentyp",
                cuenta_ahorro: "Sparkonto", cuenta_ahorro_desc: "Ideal zum Sparen",
                cuenta_corriente: "Girokonto", cuenta_corriente_desc: "Für den täglichen Gebrauch und Transaktionen",
                tarjeta_debito: "Debitkarte", tarjeta_debito_desc: "Geben Sie nur aus, was Sie haben",
                tarjeta_credito: "Kreditkarte", tarjeta_credito_desc: "Jetzt kaufen und später bezahlen",
                p4_titulo: "Registrierung bestätigen", p4_sub: "Überprüfen Sie Ihre Daten, bevor Sie das Konto erstellen.",
                anios: "Jahre", registrando: "Registrierung…", crear_cuenta: "✓ Konto erstellen",
                exito_titulo: "Konto erstellt!", exito_msg: "Ihr Konto wurde erfolgreich registriert.",
                exito_correo_aviso: "Wir haben Ihre Kartennummer, Kontonummer und PIN an folgende Adresse gesendet:",
                exito_redireccion: "Überprüfen Sie Ihren Posteingang (und Spam). Sie werden in wenigen Sekunden automatisch weitergeleitet...",
                ir_login: "Jetzt zum Login",
                error_crear: "Beim Erstellen des Kontos ist ein Fehler aufgetreten",
                atras: "Zurück", continuar: "Weiter →",
            },
            lang: { titulo: "Sprache" },
        },
    },
};

// ── Inicialización ────────────────────────────────────────────────────────────
i18n
    .use(initReactI18next)
    .init({
        resources,
        lng: localStorage.getItem("atm_idioma") || "es",
        fallbackLng: "es",
        interpolation: { escapeValue: false },
    });

export default i18n;